persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
connection_messages true

allow_anonymous false
password_file /mosquitto/data/passwords
acl_file /mosquitto/data/acl

listener 1883
protocol mqtt

listener 8883
protocol mqtt
certfile /mosquitto/certs/fullchain.pem
keyfile /mosquitto/certs/privkey.pem
tls_version tlsv1.2
require_certificate false

max_keepalive 120
max_inflight_messages 20
message_size_limit 16384